# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FF_UIViewChain' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'Masonry'

  # Pods for FF_UIViewChain

  target 'FF_UIViewChainTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FF_UIViewChainUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
